### PR TITLE
Reinvoked fontawesome-webfont

### PR DESCRIPTION
**Pull request by siad007**

### CODE REVIEW

**Comment by rvanbaalen** [comment]
Why was this ever removed? Should be pulled soon, the current release of the clean template is broken without this.

**Comment by david0** [comment]
Will this fix this issue (Arrow bullets not shown (with phpdocumentor/template-clean 1.0.5 and phpdocumentor/phpdocumentor  v2.6.1)?
image

**Comment by siad007** [comment]
@david0 yes

**Comment by siad007** [comment]
Related to https://github.com/phpDocumentor/phpDocumentor2/issues/1341

**Comment by mvriel** [comment]
Thanks for adding this in!

**Pull request merged**
