### PR TITLE
Added support for examples.

### PR DESCRIPTION
**Pull request by siad007**
Related to https://github.com/phpDocumentor/phpDocumentor2/pull/1209

### CODE REVIEW

**Comment by thebeline** [comment]
There is a pretty significant merge conflict when pulling this into develop...

both modified:      src/phpDocumentor/Plugin/Core/Transformer/Writer/Xml.php

**Comment by siad007** [comment]
Can you please explain what this change (https://github.com/phpDocumentor/template.clean/pull/34/files) has to do with `src/phpDocumentor/Plugin/Core/Transformer/Writer/Xml.php`

**Comment by thebeline** [comment]
Hmm...  Not precisely sure why this is happening...  Probably save to ignore.  Seems to be a merge conflict between the content of template.clean in the phpdoc2 repo and devleop in the phpdoc2 repo.  Odd...

**Comment by thebeline** [comment]
I did a git merge of this patch branch into the current develop branch and got that conflict.  I am probably doing something wrong.

**Comment by mvriel** [comment]
Merged #35 which contains similar changes to this PR but also contains class changes and the correct heading levels

**Pull request closed without merging**
